---
title: "Sepsis Data Report"
format: gfm
execute: 
  eval: true
  warning: false
  message: false
editor: visual
---

```{r}
#| echo: false
library(tidyverse)
library(data.table) ## For the fread function
library(lubridate)
library(dplyr)
library(googledrive)
library(kableExtra)
library(plotly)
source("sepsis_monitor_functions.R")
drive_deauth()
file_link <- "https://drive.google.com/file/d/1W6nFFYcX24ldesMLKGccEGRq-O6Zys7A/view?usp=sharing"
## All data up until now
new_data <- updateData(file_link) 

## Include only most recent data
most_recent_data <- new_data %>%
  group_by(PatientID) %>%
  filter(obsTime == max(obsTime))
timenow <- ymd_hms(now())
```

## Sepsis Patient Information

### Data last updated: `r ymd_hms(now(tzone = "America/Chicago"))`

#### Current Vitals for Patients with Sepsis

```{r}
#| echo: false
dt <- most_recent_data %>%
  filter(SepsisLabel == 1) %>%
  arrange(desc(ICULOS)) %>%
  select(PatientID, ICULOS, HR, Temp, Resp) %>%
  rename("Hours in Hospital" = ICULOS,
         "Temperature" = Temp, 
         "Respiratory Rate" = Resp, 
         "Heart Rate" = HR) 
knitr::kable(dt)


```

#### Change in Vitals for All Patients

```{r}
#| echo: false

#Change in vitals from last data point
dt2 <- new_data %>%
  group_by(PatientID) %>%
  arrange(ICULOS) %>% 
  select(PatientID, ICULOS, SepsisLabel, HR, Temp, Resp) %>%
  mutate("Heart Rate Change" = ifelse(max(ICULOS) >= 1, HR[ICULOS == max(ICULOS)] - HR[ICULOS == max(ICULOS)-1], NA),
         "Temperature Change" = ifelse(max(ICULOS) >= 1, Temp[ICULOS == max(ICULOS)] - Temp[ICULOS == max(ICULOS)-1], NA),
         "Respiration Rate Change" = ifelse(max(ICULOS) >= 1, Resp[ICULOS == max(ICULOS)] - Resp[ICULOS == max(ICULOS)-1], NA),
         SepsisLabel = ifelse(SepsisLabel == 1, "Yes", "No")) %>%
  slice_max(ICULOS) %>%
  rename("Hours in Hospital" = ICULOS,
         "Temperature" = Temp, 
         "Respiratory Rate" = Resp, 
         "Heart Rate" = HR,
         "Sepsis" = SepsisLabel)
  



knitr::kable(dt2, caption = "Change refers to change from last hour")
```

```{r}
#| echo: false

plotdf <- new_data %>%
  filter(SepsisLabel == 1)


p1 <- ggplot(data = plotdf, aes(x = ICULOS, y = HR, group = plotdf$PatientID, 
                          color = plotdf$PatientID))+
  theme_classic()+
  geom_line(size = 1.5) +
  labs(color = "Patient ID",
       x = "Hours in Hospital",
       y = "Heart Rate in Beats per Minute",
       title = "HR Over Course of Hospital Visit for Current Sepsis Patients")

  
p1 + xlim(0,60)
  
#Resp
p2 <- ggplot(data = plotdf, aes(x = ICULOS, y =Resp, group = plotdf$PatientID,
                          color = plotdf$PatientID))+
  theme_classic() + 
  geom_line(size = 1.5) +
  labs(color = "Patient ID",
       x = "Hours in Hospital",
       y = "Respiratory Rate",
       title = "Respiratory Rate Over Course of Hospital Visit for Current Sepsis Patients")

  
p2 + xlim(0,60)
  
#Temp
p3 <- ggplot(data = plotdf, aes(x = ICULOS, y =Temp, group = plotdf$PatientID,
                          color = plotdf$PatientID))+
  theme_classic() + 
  geom_point(size = 1.5) +
  labs(color = "Patient ID",
       x = "Hours in Hospital",
       y = "Temperature",
       title = "Temperature Over Course of Hospital Visit for Current Sepsis Patients") 

p3 + xlim(0,60)

```
